export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL"
export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST"
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS"
export const CLEAR_ALL_ERRORS = "CLEAR_ALL_ERRORS"